export const CLIENT_PACKET_ID = {
    getMyCharacter: 1,
    getCharacter: 2,
    changeRopa: 3,
    actPosition: 4,
    changeHeading: 5,
    deleteCharacter: 6,
    dialog: 7,
    console: 8,
    pong: 9,
    animFX: 10,
    inmo: 11,
    updateHP: 12,
    updateMaxHP: 13,
    updateMana: 14,
    telepMe: 15,
    actOnline: 19,
    consoleOnline: 20,
    actPositionServer: 21,
    actExp: 22,
    actMyLevel: 23,
    actGold: 24,
    actColorName: 25,
    changeHelmet: 26,
    changeWeapon: 27,
    error: 28,
    changeName: 29,
    getNpc: 30,
    changeShield: 31,
    putBodyAndHeadDead: 32,
    revivirUsuario: 33,
    quitarUserInvItem: 34,
    renderItem: 35,
    deleteItem: 36,
    agregarUserInvItem: 37,
    changeArrow: 38,
    blockMap: 39,
    changeObjIndex: 40,
    openTrade: 41,
    aprenderSpell: 42,
    closeForce: 43,
    nameMap: 44,
    changeBody: 45,
    navegando: 46,
    updateAgilidad: 47,
    updateFuerza: 48,
    playSound: 49,
    openBail: 50,
    closeBail: 51,
    openAdminIntervals: 52,
    panelSnapshot: 53,
    panelSnapshotChunk: 54,
    partyState: 55,
    clanState: 56,
    characterStatsSnapshot: 57,
    characterStatsSnapshotChunk: 58,
    startCastBar: 59,
    stopCastBar: 60,
    openCrafting: 61,
    closeTrade: 62,
    openMarket: 63,
    openRetos: 64,
    createProjectile: 65,
    spellProjectile: 66,
    globalNotice: 67,
    batch: 68,
    tInmo: 69,
    tUpdateHP: 70,
    tUpdateMana: 71,
    areaCharactersSnapshot: 72,
    areaNpcsSnapshot: 73,
    areaItemsSnapshot: 74,
    areaMetaSnapshot: 75,
    moveEntity: 76,
    selfFlagsDelta: 77,
    selfVitalsDelta: 78,
    selfMapMetaDelta: 79,
    spellVisual: 80,
    entityVitalsDelta: 81,
} as const;

export const SERVER_PACKET_ID = {
    changeHeading: 175,
    click: 183,
    useItemClick: 197,
    equiparItem: 210,
    connectCharacter: 212,
    position: 176,
    dialog: 221,
    ping: 184,
    attackMele: 229,
    attackRange: 236,
    attackSpell: 243,
    tirarItem: 200,
    agarrarItem: 205,
    buyItem: 214,
    sellItem: 222,
    resyncPosition: 187,
    changeSeguro: 196,
    reorderSpell: 228,
    reorderInventoryItem: 235,
    toggleHiddenSkill: 244,
    useItemU: 203,
    changeClanSeguro: 209,
    craftItem: 246,
    reorderBankItem: 230,
    changeBankTab: 216,
    depositBankGold: 224,
    withdrawBankGold: 237,
    closeTrade: 190,
    marketAction: 239,
    retosAction: 248,
} as const;

export type ClientPacketIdMap = typeof CLIENT_PACKET_ID;
export type ServerPacketIdMap = typeof SERVER_PACKET_ID;
export type ClientPacketName = keyof ClientPacketIdMap;
export type ServerPacketName = keyof ServerPacketIdMap;
export type ClientPacketId = ClientPacketIdMap[ClientPacketName];
export type ServerPacketId = ServerPacketIdMap[ServerPacketName];
